arch: Rolling_Unet_S
batch_size: 100
data_root: /data/phucnd/Bubble_Glare_Baseline/Rolling-Unet/inputs/data/Lung_AD
dataset: isic
deep_supervision: false
early_stopping: -1
epochs: 500
factor: 0.1
gamma: 0.6666666666666666
img_ext: .png
input_channels: 3
input_h: 256
input_w: 256
loss: BCEDiceLoss
lr: 0.0001
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
name: Lung
nesterov: false
num_classes: 1
num_workers: 4
optimizer: Adam
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0.0001
